name: 

on:
    push:
        branches:
            - main



jobs:
    build:
        runs-on: ubuntu-latest
     
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
         
          
        - name: Set up Node js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install protoc
          run: |
            sudo apt-get update
            sudo apt-get install -y protobuf-dev      
            sudo apt-get install -y libc6-compat
            sudo apt-get install -y protoc
        
        - name: Install dependencies
          run: npm ci

        - name: Generate gRPC code
          run: npm run grpc:generate
          
        - name: Build
          run: npm run build

        - name: Test the application
          run: |
            npm test  


           