name: 

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
     
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
                   
        - name: Set up Node js
          uses: actions/setup-node@v2
          with:
            node-version: '20'
        
        - name: Install dependencies
          run: npm install && npm install ci

        - name: Build
          run: npm run build

    Docker:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest     


           
